name: Test
on: [push]

jobs:
  Teste:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        repository: "Bds-Maneger/BDS-Common"

    - name: Package
      uses: Sirherobrine23/Action-Debian_Package@main
      with:
        SCRIPT: "script.sh"
        GIT: true
        URL: 'https://github.com/Sirherobrine23/APT_bysh23.git'
        BRANCH: 'master'
        TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish
      uses: Sirherobrine23/Action-Debian_Package_Publish@main
      with:
        REPO_PATH: 'package/main'
        PATH: "${{ env.DEB_PATH }}"
        REPOSITORY: 'https://github.com/Sirherobrine23/APT_bysh23.git'
        TOKEN: ${{ secrets.pass }}
        BRANCH: 'master'
