name: Test
on: [push]

jobs:
  Teste:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        repository: "Bds-Maneger/BDS-Common"

    - name: Teste
      uses: Sirherobrine23/Action-Debian_Package@main
      with:
        SCRIPT: "script.sh"
        GIT: true
        URL: 'https://github.com/Sirherobrine23/APT_bysh23.git'
        BRANCH: 'master'
        
    - name: List
      run: echo ${{ env.DEB_PATH }}
